# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop1945
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  # be:
  # image: nguyenhieuhero/eshopbe
  # restart: always
  # ports:
  #   - 3001:3000
  # environment:
  #   DATABASE_URL: postgresql://eshop:eshop1945@postgres:5432/mydb?schema=public
  #   JWT_AT_SECRET: bWVyaXN1
  #   JWT_RT_SECRET: bmd1eWVuaGlldWhlcm8=
  #   HASH_SECRET: dXNpcmVt"
